#pragma once
#include "esphome.h"

// AUTO-GENERATED by vESP.cloud
// Project: vESP.cloud
// Generated: 2026-01-17T09:55:59.370Z
// DO NOT EDIT - regenerate from editor

// View IDs: TEMPS -> VIEW_DETAIL_TEMPS, VACUUM -> VIEW_DETAIL_VACUUM, LIGHTS -> VIEW_DETAIL_LIGHTS, CLIMATE -> VIEW_DETAIL_CLIMATE
enum ViewState {
  DASHBOARD = 0,
  VIEW_DETAIL_TEMPS = 1,
  VIEW_DETAIL_VACUUM = 2,
  VIEW_DETAIL_LIGHTS = 3,
  VIEW_DETAIL_CLIMATE = 4,
};

// Navigation constants
const int DISPLAY_WIDTH = 240;
const int DISPLAY_HEIGHT = 320;
const int DEFAULT_HEADER_HEIGHT = 45;

// Scroll bounds for detail views (height - headerHeight)
const int SCROLL_Y_MAX_VIEW_DETAIL_TEMPS = 275;  // 320 - 45
const int SCROLL_Y_MAX_VIEW_DETAIL_VACUUM = 355;  // 400 - 45
const int SCROLL_Y_MAX_VIEW_DETAIL_LIGHTS = 275;  // 320 - 45
const int SCROLL_Y_MAX_VIEW_DETAIL_CLIMATE = 440;  // 500 - 60

// Global display state
struct DisplayState {
  // Navigation
  int mainPageIndex = 0;
  int numPages = 4;
  ViewState currentView = DASHBOARD;
  int scrollY = 0;
  int maxScrollY = 0;

  // Sensor fields
  float outsideTemp = 0.0f;
  float humidity = 0.0f;
  std::string vacuumStatus = "offline";
  int vacuumBattery = 0;
  bool lightsOn = false;

  // Helper: check if we're in the main dashboard
  bool isDashboard() const {
    return currentView == DASHBOARD;
  }

  // Update scroll bounds based on current view
  void updateScrollBounds() {
    switch (currentView) {
      case VIEW_DETAIL_TEMPS:
        maxScrollY = SCROLL_Y_MAX_VIEW_DETAIL_TEMPS;
        break;
      case VIEW_DETAIL_VACUUM:
        maxScrollY = SCROLL_Y_MAX_VIEW_DETAIL_VACUUM;
        break;
      case VIEW_DETAIL_LIGHTS:
        maxScrollY = SCROLL_Y_MAX_VIEW_DETAIL_LIGHTS;
        break;
      case VIEW_DETAIL_CLIMATE:
        maxScrollY = SCROLL_Y_MAX_VIEW_DETAIL_CLIMATE;
        break;
      default:
        maxScrollY = 0;
    }
  }
};

// Global state instance
DisplayState gState;
