font:
  - file: "gfonts://Share Tech Mono"
    id: font_tiny
    size: 12
    glyphs: '!"%()+*-.,/:;<=>?@[\]^_`{|}~ 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'

  - file: "gfonts://Share Tech Mono"
    id: font_small
    size: 16
    glyphs: '!"%()+*-.,/:;<=>?@[\]^_`{|}~ 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'

  - file: "gfonts://Share Tech Mono"
    id: font_medium
    size: 22
    glyphs: '!"%()+*-.,/:;<=>?@[\]^_`{|}~ 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'

  - file: "gfonts://Share Tech Mono"
    id: font_large
    size: 32
    glyphs: '!"%()+*-.,/:;<=>?@[\]^_`{|}~ 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÄÖÜäöüß'