/**
 * Unit tests for ESPHome YAML generator (LVGL)
 *
 * Tests the generateESPHomeYAML function and helper utilities.
 */

import { describe, test, expect } from "bun:test";
import { generateESPHomeYAML, entityToId } from "../esphome";
import type { Project } from "@esphome-designer/schema";

function makeProject(overrides: Partial<Project> = {}): Project {
  return {
    name: "Test Display",
    display: { width: 480, height: 480, platform: "ili9xxx" },
    dashboardPages: [],
    detailViews: [],
    ...overrides,
  };
}

describe("ESPHome YAML Generator (LVGL)", () => {
  describe("generateESPHomeYAML", () => {
    test("generates valid YAML header with project info", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("# Generated by ESPHome Designer");
      expect(yaml).toContain("# Project: Test Display");
      expect(yaml).toContain("Generated:");
    });

    test("generates device name from project name", () => {
      const yaml = generateESPHomeYAML(
        makeProject({ name: "My Home Display" }),
      );
      expect(yaml).toContain("device_name: my-home-display");
    });

    test("includes inline hardware configuration", () => {
      const yaml = generateESPHomeYAML(makeProject());
      // Check for inline hardware components instead of package include
      expect(yaml).toContain("i2c:");
      expect(yaml).toContain("touchscreen:");
      expect(yaml).toContain("platform: gt911");
      expect(yaml).toContain("spi:");
      expect(yaml).toContain("display:");
      expect(yaml).toContain("platform: st7701s");
      expect(yaml).toContain("light:");
      expect(yaml).toContain("platform: monochromatic");
    });

    test("does not include C++ headers", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).not.toContain("includes:");
      expect(yaml).not.toContain("display_renderer.h");
      expect(yaml).not.toContain("state_manager.h");
      expect(yaml).not.toContain("touch_handler.h");
      expect(yaml).not.toContain("render_helpers.h");
      expect(yaml).not.toContain("render_pages.h");
      expect(yaml).not.toContain("render_details.h");
    });

    test("does not include manual display lambda", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).not.toContain("renderDisplay(it)");
      expect(yaml).not.toContain("lambda: |-\n      renderDisplay");
    });

    test("generates LVGL page_wrap configuration", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("lvgl:");
      expect(yaml).toContain("page_wrap: true");
      expect(yaml).toContain("pages:");
    });

    test("generates LVGL pages from dashboard pages", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            { id: "page-0", name: "Home", components: [] },
            { id: "page-1", name: "Music", components: [] },
          ],
        }),
      );
      expect(yaml).toContain("# Home");
      expect(yaml).toContain("- id: page_0");
      expect(yaml).toContain("# Music");
      expect(yaml).toContain("- id: page_1");
    });

    test("generates label widget from text component", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Home",
              components: [
                {
                  id: "text-1",
                  type: "text",
                  text: "Hello World",
                  position: { x: 10, y: 20 },
                  fontSize: "large",
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("- label:");
      expect(yaml).toContain('text: "Hello World"');
      expect(yaml).toContain("x: 10");
      expect(yaml).toContain("y: 20");
      expect(yaml).toContain("text_font: montserrat_28");
    });

    test("generates button widget with on_click script", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Controls",
              components: [
                {
                  id: "btn-1",
                  type: "button",
                  label: "Toggle Light",
                  position: { x: 50, y: 100 },
                  size: { width: 200, height: 60 },
                  pressAction: {
                    type: "SERVICE_CALL",
                    service: "light.toggle",
                    target: { entityId: "light.living_room" },
                  },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("- button:");
      expect(yaml).toContain("checkable: true");
      expect(yaml).toContain(
        "- script.execute: script_light_toggle_light_living_room",
      );
      expect(yaml).toContain("script:");
      expect(yaml).toContain(
        "id: script_light_toggle_light_living_room",
      );
      expect(yaml).toContain("service: light.toggle");
      expect(yaml).toContain("entity_id: light.living_room");
    });

    test("generates binary sensor for button targeting a light", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Controls",
              components: [
                {
                  id: "btn-1",
                  type: "button",
                  label: "Light",
                  position: { x: 0, y: 0 },
                  pressAction: {
                    type: "SERVICE_CALL",
                    service: "light.toggle",
                    target: { entityId: "light.bedroom" },
                  },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("binary_sensor:");
      expect(yaml).toContain("entity_id: light.bedroom");
      expect(yaml).toContain("lvgl.widget.update:");
      expect(yaml).toContain("checked: !lambda return x;");
    });

    test("generates sensor with lvgl.label.update for text binding", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Sensors",
              components: [
                {
                  id: "temp-1",
                  type: "text",
                  position: { x: 10, y: 50 },
                  textBinding: { entityId: "sensor.temperature" },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("sensor:");
      expect(yaml).toContain("entity_id: sensor.temperature");
      expect(yaml).toContain("lvgl.label.update:");
      expect(yaml).toContain("id: w_temp_1");
      expect(yaml).toContain('format: "%.1f"');
      expect(yaml).toContain("args: [x]");
    });

    test("generates arc widget from gauge component", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Dashboard",
              components: [
                {
                  id: "gauge-1",
                  type: "gauge",
                  min: 0,
                  max: 100,
                  position: { x: 100, y: 100 },
                  size: { width: 120, height: 120 },
                  valueBinding: { entityId: "sensor.humidity" },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("- arc:");
      expect(yaml).toContain("min_value: 0");
      expect(yaml).toContain("max_value: 100");
      expect(yaml).toContain("adjustable: false");
      expect(yaml).toContain("lvgl.arc.update:");
    });

    test("generates slider widget", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Controls",
              components: [
                {
                  id: "slider-1",
                  type: "slider",
                  min: 0,
                  max: 255,
                  position: { x: 20, y: 200 },
                  size: { width: 300, height: 40 },
                  valueBinding: { entityId: "sensor.brightness" },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("- slider:");
      expect(yaml).toContain("min_value: 0");
      expect(yaml).toContain("max_value: 255");
      expect(yaml).toContain("lvgl.slider.update:");
    });

    test("includes WiFi configuration with captive portal", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("wifi:");
      expect(yaml).toContain("ap:");
      expect(yaml).toContain("captive_portal:");
      expect(yaml).toContain("esp32_improv:");
    });

    test("includes API and OTA configuration", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("api:");
      expect(yaml).toContain("reboot_timeout: 15min");
      expect(yaml).toContain("ota:");
      expect(yaml).toContain("platform: esphome");
    });

    test("includes time configuration for SNTP", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("time:");
      expect(yaml).toContain("platform: sntp");
      expect(yaml).toContain("id: sntp_time");
    });

    test("includes Bluetooth proxy configuration", () => {
      const yaml = generateESPHomeYAML(makeProject());
      expect(yaml).toContain("esp32_ble_tracker:");
      expect(yaml).toContain("bluetooth_proxy:");
      expect(yaml).toContain("active: true");
    });

    test("handles project name with special characters", () => {
      const yaml = generateESPHomeYAML(
        makeProject({ name: "Living Room  Display  v2" }),
      );
      expect(yaml).toContain("device_name: living-room-display-v2");
    });

    test("lists dashboard pages in comments", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            { id: "page-0", name: "Home", components: [] },
            { id: "page-1", name: "Music", components: [] },
            { id: "page-2", name: "Climate", components: [] },
          ],
        }),
      );
      expect(yaml).toContain("# Total dashboard pages: 3");
      expect(yaml).toContain("# Page 0: Home");
      expect(yaml).toContain("# Page 1: Music");
      expect(yaml).toContain("# Page 2: Climate");
    });

    test("generates page background color", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Blue Page",
              backgroundColor: { r: 0, g: 0, b: 255 },
              components: [],
            },
          ],
        }),
      );
      expect(yaml).toContain("bg_color: 0x0000FF");
    });

    test("generates container as obj with flex layout", () => {
      const yaml = generateESPHomeYAML(
        makeProject({
          dashboardPages: [
            {
              id: "page-0",
              name: "Layout",
              components: [
                {
                  id: "container-1",
                  type: "container",
                  label: "Items",
                  position: { x: 10, y: 50 },
                  size: { width: 400, height: 300 },
                },
              ],
            },
          ],
        }),
      );
      expect(yaml).toContain("- obj:");
      expect(yaml).toContain("scrollbar_mode: auto");
      expect(yaml).toContain("type: flex");
      expect(yaml).toContain("flex_flow: COLUMN");
    });
  });

  describe("entityToId", () => {
    test("converts entity ID to valid identifier", () => {
      expect(entityToId("sensor.outside_temperature")).toBe(
        "ha_sensor_outside_temperature",
      );
    });

    test("handles nested domain entities", () => {
      expect(entityToId("light.living_room")).toBe("ha_light_living_room");
    });

    test("handles binary sensors", () => {
      expect(entityToId("binary_sensor.motion")).toBe(
        "ha_binary_sensor_motion",
      );
    });

    test("handles climate entities", () => {
      expect(entityToId("climate.hvac")).toBe("ha_climate_hvac");
    });
  });
});
