/**
 * Unit tests for render pages code generator
 *
 * Tests the generateRenderPages function which creates C++ render
 * functions for dashboard pages and their components.
 */

import { describe, test, expect } from "bun:test";
import { generateRenderPages } from "../render-pages";
import type { Project, Page, TextComponent, ButtonComponent, ContainerComponent, ConditionalAreaComponent, ConditionalVariant, EntityCondition, CompoundCondition, NotCondition } from "@esphome-designer/schema";

describe("Render Pages Generator", () => {
  describe("generateRenderPages", () => {
    test("generates valid C++ header with pragma once", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("#pragma once");
      expect(cpp).toContain('#include "esphome.h"');
      expect(cpp).toContain('#include "state_manager.h"');
      expect(cpp).toContain('#include "render_helpers.h"');
    });

    test("includes project info in header comment", () => {
      const project: Project = {
        name: "Home Display",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("AUTO-GENERATED by ESPHome Designer");
      expect(cpp).toContain("Project: Home Display");
      expect(cpp).toContain("Generated:");
    });

    test("includes font extern declarations", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("extern esphome::font::Font *font_tiny;");
      expect(cpp).toContain("extern esphome::font::Font *font_small;");
      expect(cpp).toContain("extern esphome::font::Font *font_medium;");
      expect(cpp).toContain("extern esphome::font::Font *font_large;");
    });

    test("generates render function for each dashboard page", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [] },
          { id: "page-1", name: "Music", components: [] },
          { id: "page-2", name: "Climate", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("void renderPage0(display::Display& it) {");
      expect(cpp).toContain("void renderPage1(display::Display& it) {");
      expect(cpp).toContain("void renderPage2(display::Display& it) {");
    });

    test("includes page name in comment", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Status Dashboard", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Dashboard Page 0: Status Dashboard");
    });

    test("handles empty pages gracefully", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [{ id: "page-0", name: "Empty", components: [] }],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// (No components defined for this page)");
    });

    test("generates no page functions for empty dashboard", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).not.toContain("void renderPage0");
    });
  });

  describe("Page Background Color", () => {
    test("fills with background color when specified", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          {
            id: "page-0",
            name: "Colored",
            backgroundColor: { r: 20, g: 30, b: 40 },
            components: [],
          },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("it.fill(Color(20, 30, 40));");
    });

    test("does not fill when no background color specified", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Default", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).not.toContain("it.fill(Color");
    });
  });

  describe("Text Component Generation", () => {
    test("generates static text component", () => {
      const textComponent: TextComponent = {
        id: "title-text",
        type: "text",
        position: { x: 10, y: 50 },
        text: "Hello World",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Text: title-text");
      expect(cpp).toContain('it.print(10, 50, font_medium, Theme::FOREGROUND, "Hello World");');
    });

    test("uses small font for small fontSize", () => {
      const textComponent: TextComponent = {
        id: "small-text",
        type: "text",
        position: { x: 0, y: 0 },
        text: "Small",
        fontSize: "small",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("font_small");
    });

    test("uses large font for large fontSize", () => {
      const textComponent: TextComponent = {
        id: "large-text",
        type: "text",
        position: { x: 0, y: 0 },
        text: "Large",
        fontSize: "large",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("font_large");
    });

    test("applies custom color to text", () => {
      const textComponent: TextComponent = {
        id: "colored-text",
        type: "text",
        position: { x: 0, y: 0 },
        text: "Red Text",
        color: { r: 255, g: 0, b: 0 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("Color(255, 0, 0)");
    });

    test("handles text with entity binding", () => {
      const textComponent: TextComponent = {
        id: "bound-text",
        type: "text",
        position: { x: 20, y: 100 },
        text: "Temperature: ",
        textBinding: { entityId: "sensor.temperature" },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Text: bound-text (bound to sensor.temperature)");
    });

    test("handles empty text gracefully", () => {
      const textComponent: TextComponent = {
        id: "empty-text",
        type: "text",
        position: { x: 0, y: 0 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [textComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain('it.print(0, 0, font_medium, Theme::FOREGROUND, "");');
    });
  });

  describe("Button Component Generation", () => {
    test("generates button with label", () => {
      const buttonComponent: ButtonComponent = {
        id: "test-button",
        type: "button",
        position: { x: 10, y: 100 },
        size: { width: 80, height: 40 },
        label: "Click Me",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [buttonComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Button: test-button");
      expect(cpp).toContain("it.filled_rectangle(10, 100, 80, 40");
      expect(cpp).toContain("it.rectangle(10, 100, 80, 40, Theme::ACCENT);");
      expect(cpp).toContain('"Click Me"');
    });

    test("uses custom background color for button", () => {
      const buttonComponent: ButtonComponent = {
        id: "colored-button",
        type: "button",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 50 },
        backgroundColor: { r: 0, g: 128, b: 255 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [buttonComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("Color(0, 128, 255)");
    });

    test("uses default background when not specified", () => {
      const buttonComponent: ButtonComponent = {
        id: "default-button",
        type: "button",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 50 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [buttonComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("Theme::BACKGROUND_SECONDARY");
    });

    test("centers button label text", () => {
      const buttonComponent: ButtonComponent = {
        id: "centered-button",
        type: "button",
        position: { x: 20, y: 80 },
        size: { width: 200, height: 60 },
        label: "Centered",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [buttonComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      // Button text should be centered: x + width/2, y + height/2
      expect(cpp).toContain("20 + 200/2");
      expect(cpp).toContain("80 + 60/2");
      expect(cpp).toContain("TextAlign::CENTER");
    });

    test("handles button with empty label", () => {
      const buttonComponent: ButtonComponent = {
        id: "no-label-button",
        type: "button",
        position: { x: 0, y: 0 },
        size: { width: 50, height: 50 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [buttonComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain('""');
    });
  });

  describe("Container Component Generation", () => {
    test("generates container with label", () => {
      const containerComponent: ContainerComponent = {
        id: "info-box",
        type: "container",
        position: { x: 5, y: 50 },
        size: { width: 230, height: 100 },
        label: "Information",
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [containerComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Container: info-box");
      expect(cpp).toContain('drawThemedBox(it, 5, 50, 230, 100, "Information");');
    });

    test("generates container without label", () => {
      const containerComponent: ContainerComponent = {
        id: "plain-box",
        type: "container",
        position: { x: 10, y: 60 },
        size: { width: 220, height: 80 },
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [containerComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain('drawThemedBox(it, 10, 60, 220, 80, "");');
    });
  });

  describe("Unsupported Components", () => {
    test("adds comment for unsupported component types", () => {
      const gaugeComponent = {
        id: "gauge-1",
        type: "gauge",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        min: 0,
        max: 100,
      } as any;

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [gaugeComponent] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Unsupported component type for pages: gauge");
    });
  });

  describe("Multiple Components", () => {
    test("generates code for multiple components in order", () => {
      const components = [
        {
          id: "text-1",
          type: "text",
          position: { x: 10, y: 10 },
          text: "First",
        } as TextComponent,
        {
          id: "button-1",
          type: "button",
          position: { x: 10, y: 50 },
          size: { width: 100, height: 40 },
          label: "Second",
        } as ButtonComponent,
        {
          id: "text-2",
          type: "text",
          position: { x: 10, y: 100 },
          text: "Third",
        } as TextComponent,
      ];

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      const text1Index = cpp.indexOf("// Text: text-1");
      const button1Index = cpp.indexOf("// Button: button-1");
      const text2Index = cpp.indexOf("// Text: text-2");

      expect(text1Index).toBeLessThan(button1Index);
      expect(button1Index).toBeLessThan(text2Index);
    });
  });

  describe("Code Quality", () => {
    test("generates balanced braces", () => {
      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          {
            id: "page-0",
            name: "Home",
            components: [
              { id: "text-1", type: "text", position: { x: 0, y: 0 }, text: "Test" } as TextComponent,
              { id: "btn-1", type: "button", position: { x: 0, y: 50 }, size: { width: 100, height: 40 } } as ButtonComponent,
            ],
          },
          { id: "page-1", name: "Second", components: [] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      const openBraces = (cpp.match(/{/g) || []).length;
      const closeBraces = (cpp.match(/}/g) || []).length;
      expect(openBraces).toBe(closeBraces);
    });
  });

  describe("Conditional Area Component Generation", () => {
    test("generates conditional area with single variant", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "cond-1",
        type: "conditional_area",
        position: { x: 10, y: 20 },
        size: { width: 100, height: 50 },
        variants: [
          {
            id: "default",
            name: "Default State",
            components: [
              { id: "text-1", type: "text", position: { x: 5, y: 5 }, text: "Hello" } as TextComponent,
            ],
          },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Conditional Area: cond-1");
      expect(cpp).toContain("// Variant: Default State");
    });

    test("applies clipping by default", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "clipped-area",
        type: "conditional_area",
        position: { x: 10, y: 20 },
        size: { width: 100, height: 50 },
        variants: [{ id: "v1", name: "V1", components: [] }],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("it.start_clipping(10, 20, 100, 50)");
      expect(cpp).toContain("it.end_clipping()");
    });

    test("disables clipping when clipContent is false", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "unclipped-area",
        type: "conditional_area",
        position: { x: 10, y: 20 },
        size: { width: 100, height: 50 },
        clipContent: false,
        variants: [{ id: "v1", name: "V1", components: [] }],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).not.toContain("start_clipping");
      expect(cpp).not.toContain("end_clipping");
    });

    test("generates entity condition with eq operator", () => {
      const condition: EntityCondition = {
        type: "entity",
        entityId: "light.living_room",
        operator: "eq",
        value: "on",
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "light-status",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "on", name: "Light On", condition, components: [] },
          { id: "off", name: "Light Off", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain('id(ha_light_living_room).state == "on"');
      expect(cpp).toContain("// Variant: Light On");
      expect(cpp).toContain("// Variant: Light Off (Default)");
    });

    test("generates all comparison operators", () => {
      const operators = [
        { op: "neq", expected: "!=" },
        { op: "gt", expected: ">" },
        { op: "gte", expected: ">=" },
        { op: "lt", expected: "<" },
        { op: "lte", expected: "<=" },
      ] as const;

      for (const { op, expected } of operators) {
        const condition: EntityCondition = {
          type: "entity",
          entityId: "sensor.temp",
          operator: op,
          value: 20,
        };

        const conditionalArea: ConditionalAreaComponent = {
          id: "test-area",
          type: "conditional_area",
          position: { x: 0, y: 0 },
          size: { width: 100, height: 100 },
          variants: [
            { id: "cond", name: "Conditional", condition, components: [] },
            { id: "default", name: "Default", components: [] },
          ],
        };

        const project: Project = {
          name: "Test",
          display: { width: 240, height: 320, platform: "ili9xxx" },
          dashboardPages: [
            { id: "page-0", name: "Home", components: [conditionalArea] },
          ],
          detailViews: [],
        };

        const cpp = generateRenderPages(project);
        expect(cpp).toContain(`id(ha_sensor_temp).state ${expected} 20`);
      }
    });

    test("generates contains operator", () => {
      const condition: EntityCondition = {
        type: "entity",
        entityId: "sensor.status",
        operator: "contains",
        value: "error",
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "status-area",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "error", name: "Has Error", condition, components: [] },
          { id: "ok", name: "OK", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain('.find("error") != std::string::npos');
    });

    test("generates compound AND condition", () => {
      const condition: CompoundCondition = {
        type: "compound",
        operator: "and",
        conditions: [
          { type: "entity", entityId: "light.a", operator: "eq", value: "on" },
          { type: "entity", entityId: "light.b", operator: "eq", value: "on" },
        ],
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "multi-light",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "both-on", name: "Both On", condition, components: [] },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("&&");
      expect(cpp).toContain('id(ha_light_a).state == "on"');
      expect(cpp).toContain('id(ha_light_b).state == "on"');
    });

    test("generates compound OR condition", () => {
      const condition: CompoundCondition = {
        type: "compound",
        operator: "or",
        conditions: [
          { type: "entity", entityId: "light.a", operator: "eq", value: "on" },
          { type: "entity", entityId: "light.b", operator: "eq", value: "on" },
        ],
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "any-light",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "any-on", name: "Any On", condition, components: [] },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("||");
    });

    test("generates NOT condition", () => {
      const condition: NotCondition = {
        type: "not",
        condition: { type: "entity", entityId: "binary_sensor.motion", operator: "eq", value: "on" },
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "no-motion",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "no-motion", name: "No Motion", condition, components: [] },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("!(");
      expect(cpp).toContain('id(ha_binary_sensor_motion).state == "on"');
    });

    test("sorts variants by priority (highest first)", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "priority-area",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          {
            id: "low",
            name: "Low Priority",
            priority: 1,
            condition: { type: "entity", entityId: "sensor.a", operator: "eq", value: 1 },
            components: [],
          },
          {
            id: "high",
            name: "High Priority",
            priority: 10,
            condition: { type: "entity", entityId: "sensor.b", operator: "eq", value: 1 },
            components: [],
          },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      // High priority should appear first in the if chain
      const highIndex = cpp.indexOf("High Priority");
      const lowIndex = cpp.indexOf("Low Priority");
      expect(highIndex).toBeLessThan(lowIndex);
    });

    test("adjusts child component positions to be absolute", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "positioned-area",
        type: "conditional_area",
        position: { x: 50, y: 100 },
        size: { width: 100, height: 100 },
        variants: [
          {
            id: "default",
            name: "Default",
            components: [
              { id: "child-text", type: "text", position: { x: 10, y: 20 }, text: "Child" } as TextComponent,
            ],
          },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      // Child at (10, 20) + parent at (50, 100) = (60, 120)
      expect(cpp).toContain("it.print(60, 120,");
    });

    test("generates if/else if/else chain for multiple conditions", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "multi-cond",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          {
            id: "first",
            name: "First",
            condition: { type: "entity", entityId: "sensor.a", operator: "eq", value: 1 },
            components: [],
          },
          {
            id: "second",
            name: "Second",
            condition: { type: "entity", entityId: "sensor.b", operator: "eq", value: 2 },
            components: [],
          },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("if (");
      expect(cpp).toContain("else if (");
      expect(cpp).toContain("else {");
    });

    test("handles nested components in variants", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "nested-area",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 200, height: 200 },
        variants: [
          {
            id: "complex",
            name: "Complex Layout",
            components: [
              { id: "text-1", type: "text", position: { x: 10, y: 10 }, text: "Title" } as TextComponent,
              { id: "btn-1", type: "button", position: { x: 10, y: 40 }, size: { width: 80, height: 30 }, label: "Click" } as ButtonComponent,
              { id: "container-1", type: "container", position: { x: 10, y: 80 }, size: { width: 180, height: 100 }, label: "Box" } as ContainerComponent,
            ],
          },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("// Text: text-1");
      expect(cpp).toContain("// Button: btn-1");
      expect(cpp).toContain("// Container: container-1");
    });

    test("generates balanced braces for conditional areas", () => {
      const conditionalArea: ConditionalAreaComponent = {
        id: "balanced-area",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          {
            id: "v1",
            name: "V1",
            condition: { type: "entity", entityId: "sensor.a", operator: "eq", value: 1 },
            components: [{ id: "t1", type: "text", position: { x: 0, y: 0 }, text: "A" } as TextComponent],
          },
          {
            id: "v2",
            name: "V2",
            condition: { type: "entity", entityId: "sensor.b", operator: "eq", value: 2 },
            components: [{ id: "t2", type: "text", position: { x: 0, y: 0 }, text: "B" } as TextComponent],
          },
          { id: "default", name: "Default", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      const openBraces = (cpp.match(/{/g) || []).length;
      const closeBraces = (cpp.match(/}/g) || []).length;
      expect(openBraces).toBe(closeBraces);
    });

    test("handles numeric values in conditions", () => {
      const condition: EntityCondition = {
        type: "entity",
        entityId: "sensor.temperature",
        operator: "gt",
        value: 25.5,
      };

      const conditionalArea: ConditionalAreaComponent = {
        id: "temp-area",
        type: "conditional_area",
        position: { x: 0, y: 0 },
        size: { width: 100, height: 100 },
        variants: [
          { id: "hot", name: "Hot", condition, components: [] },
          { id: "cool", name: "Cool", components: [] },
        ],
      };

      const project: Project = {
        name: "Test",
        display: { width: 240, height: 320, platform: "ili9xxx" },
        dashboardPages: [
          { id: "page-0", name: "Home", components: [conditionalArea] },
        ],
        detailViews: [],
      };

      const cpp = generateRenderPages(project);

      expect(cpp).toContain("id(ha_sensor_temperature).state > 25.5");
    });
  });
});
