/**
 * C++ Renderer Code Generator
 *
 * Generates C++ rendering code from the project schema.
 */

import type {
  Component,
  Project,
  StateField
} from "@esphome-designer/schema";
import { assert } from "$lib/utils";

type EntityId = string;
type StateFieldMap = Map<EntityId, StateField>;

export function generateCppRenderer(project: Project): string {
  const lines: string[] = [];

  // Create a lookup map for state fields for efficient access
  const stateFields: StateFieldMap = new Map();
  project.state?.fields?.forEach(field => {
    stateFields.set(field.haEntity, field);
  });

  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by ESPHome Designer`);
  lines.push(` * Project: ${project.name}`);
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`#pragma once`);
  lines.push(`#include "esphome.h"`);
  lines.push(`#include "state_manager.h"`);
  lines.push(`#include "render_helpers.h"`);
  lines.push(``);

  // Generate page render functions
  project.dashboardPages.forEach((page, i) => {
    lines.push(generateViewRenderer(page, `Page${i}`, project, stateFields));
    lines.push(``);
  });

  // Generate detail view render functions
  project.detailViews.forEach((view) => {
    const safeId = view.id.toUpperCase().replace(/-/g, '_');
    lines.push(generateViewRenderer(view, `Detail_${safeId}`, project, stateFields, true));
    lines.push(``);
  });

  // Main render dispatcher
  lines.push(`void renderDisplay(display::Display& it) {`);
  lines.push(`  it.fill(Theme::BACKGROUND);`);
  lines.push(``);
  lines.push(`  if (gState.isDashboard()) {`);
  lines.push(`    drawCommonHeader(it);`);
  lines.push(`    switch (gState.mainPageIndex) {`);
  project.dashboardPages.forEach((_, i) => {
    lines.push(`      case ${i}: renderPage${i}(it); break;`);
  });
  lines.push(`    }`);
  lines.push(`    drawPageIndicator(it, gState.mainPageIndex, ${project.dashboardPages.length});`);
  lines.push(`  } else {`);
  lines.push(`    switch (gState.currentView) {`);
  project.detailViews.forEach((view) => {
    const safeId = view.id.toUpperCase().replace(/-/g, '_');
    lines.push(`      case VIEW_DETAIL_${safeId}: renderDetail_${safeId}(it); break;`);
  });
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);

  return lines.join("\n");
}

function generateViewRenderer(view: any, name: string, project: Project, stateFields: StateFieldMap, isDetail = false): string {
  const lines: string[] = [];
  lines.push(`void render${name}(display::Display& it) {`);

  if (isDetail) {
    lines.push(`  // Detail view with scroll offset and fixed header`);
    lines.push(`  int ly = 45; // Local Y starts after header`);
    lines.push(`  auto getSY = [&](int y) { return y + gState.scrollY; };`);
    lines.push(``);
  }

  view.components.forEach((comp: Component) => {
    lines.push(generateComponentCode(comp, project, stateFields, isDetail));
  });

  if (isDetail) {
    lines.push(``);
    lines.push(`  // Draw Header Last (Always On Top)`);
    lines.push(`  it.fill_rectangle(0, 0, 240, 45, Theme::BACKGROUND);`);
    lines.push(`  it.line(0, 44, 240, 44, Theme::ACCENT);`);
    lines.push(`  it.printf(120, 22, id(font_medium), Theme::FOREGROUND, TextAlign::CENTER, "${view.title.toUpperCase()}");`);
    lines.push(`  // Back Button`);
    lines.push(`  it.filled_rectangle(5, 8, 50, 28, Theme::BACKGROUND_SECONDARY);`);
    lines.push(`  it.rectangle(5, 8, 50, 28, Theme::ACCENT);`);
    lines.push(`  it.print(30, 22, id(font_small), Theme::FOREGROUND, TextAlign::CENTER, "< BACK");`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

function generateComponentCode(comp: Component, project: Project, stateFields: StateFieldMap, isDetail: boolean): string {
  const yCoord = isDetail ? `getSY(${comp.position.y})` : comp.position.y;

  switch (comp.type) {
    case "container":
      assert(comp.size, "Container component must have size defined");
      return `  drawThemedBox(it, ${comp.position.x}, ${yCoord}, ${comp.size.width}, ${comp.size.height}, "${(comp as any).label ?? ""}");`;

    case "text":
      return generateTextCode(comp, yCoord, stateFields);

    case "button":
      assert(project.theme, "Project theme must be defined to generate button code");
      return generateButtonCode(comp, yCoord, project.theme);

    case "procedural_icon":
      return `  // Procedural Icon: ${comp.iconType} at (${comp.position.x}, ${yCoord})`;

    default:
      return `  // Unsupported component: ${comp.type}`;
  }
}

function generateTextCode(comp: any, y: string | number, stateFields: StateFieldMap): string {
  const color = comp.color ? `Color(${comp.color.r}, ${comp.color.g}, ${comp.color.b})` : "Theme::FOREGROUND";
  const font = comp.fontSize === "small" ? "id(font_small)" : comp.fontSize === "large" ? "id(font_large)" : "id(font_medium)";

  if (comp.textBinding) {
    const entityId = comp.textBinding.entityId;
    const field = stateFields.get(entityId);

    if (!field) {
      return `  // ERROR: Text component "${comp.id}" has binding to HA entity "${entityId}" but no corresponding state field was defined.`;
    }

    if (field.cppType === 'std::string') {
      const stateVar = `gState.${field.name}.c_str()`;
      return `  it.printf(${comp.position.x}, ${y}, ${font}, ${color}, TextAlign::TOP_LEFT, "%s", ${stateVar});`;
    } else {
      // For numeric types, use a buffer to format the string
      return `  {\n    char buffer[32];\n    snprintf(buffer, sizeof(buffer), "%.0f", gState.${field.name});\n    it.print(${comp.position.x}, ${y}, ${font}, ${color}, TextAlign::TOP_LEFT, buffer);\n  }`;
    }
  }

  return `  it.print(${comp.position.x}, ${y}, ${font}, ${color}, TextAlign::TOP_LEFT, "${comp.text ?? ""}");`;
}

function generateButtonCode(comp: any, y: string | number, theme: any): string {
  const x = comp.position.x;
  const w = comp.size.width;
  const h = comp.size.height;
  const shadow = theme.style.buttonShadow ? `3` : `0`;

  return `
  {
    // Button: ${comp.id}
    it.filled_rectangle(${x} + ${shadow}, ${y} + ${shadow}, ${w} - ${shadow}, ${h} - ${shadow}, Theme::BACKGROUND);
    it.filled_rectangle(${x}, ${y}, ${w} - ${shadow}, ${h} - ${shadow}, Theme::BACKGROUND_SECONDARY);
    it.rectangle(${x}, ${y}, ${w} - ${shadow}, ${h} - ${shadow}, Theme::ACCENT);
    it.printf(${x} + ${w}/2, ${y} + ${h}/2, id(font_medium), Theme::FOREGROUND, TextAlign::CENTER, "${comp.label ?? ""}");
  }`;
}
