/**
 * ESPHome YAML Code Generator
 *
 * Generates ESPHome configuration from the project schema.
 */

import type { Project, Component } from "@esphome-designer/schema";

export function generateESPHomeYAML(project: Project): string {
  const lines: string[] = [];

  lines.push(`# ============================================`);
  lines.push(`# Generated by ESPHome Designer`);
  lines.push(`# Project: ${project.name}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push(`# ============================================`);
  lines.push(``);

  // Substitutions
  const deviceName = project.name.toLowerCase().replace(/\s+/g, "-");
  lines.push(`substitutions:`);
  lines.push(`  device_name: ${deviceName}`);
  lines.push(``);

  lines.push(`packages:`);
  lines.push(`  sensors: !include sensors.yaml`);
  lines.push(``);

  // ESPHome core config
  lines.push(`esphome:`);
  lines.push(`  name: \${device_name}`);
  lines.push(`  includes:`);
  lines.push(`    - includes/display_renderer.h`);
  lines.push(`    - includes/state_manager.h`);
  lines.push(`    - includes/touch_handler.h`);
  lines.push(``);

  lines.push(`esp32:`);
  lines.push(`  board: esp32-s3-devkitc-1`);
  lines.push(`  framework:`);
  lines.push(`    type: esp-idf`);

  lines.push(``);
  lines.push(`spi:`);
  lines.push(`  id: spi_lcd`);
  lines.push(`  clk_pin: GPIO40`);
  lines.push(`  mosi_pin: GPIO45`);

  // Display hardware config
  lines.push(`display:`);
  lines.push(`  - platform: ${project.display.platform}`);
  lines.push(`    model: ST7789V`);
  lines.push(`    id: main_display`);
  lines.push(`    dc_pin: GPIO41`);
  lines.push(`    reset_pin: GPIO39`);
  lines.push(`    cs_pin: GPIO42`);
  lines.push(`    spi_id: spi_lcd`);
  lines.push(`    invert_colors: true`);
  lines.push(`    dimensions:`);
  lines.push(`      width: ${project.display.width}`);
  lines.push(`      height: ${project.display.height}`);
  lines.push(`    lambda: |-`);
  lines.push(`      renderDisplay(it);`);
  lines.push(``);

  // Fonts
  lines.push(`font:`);
  lines.push(`  - file: "gfonts://Share Tech Mono"`);
  lines.push(`    id: font_small`);
  lines.push(`    size: 12`);
  lines.push(`  - file: "gfonts://Share Tech Mono"`);
  lines.push(`    id: font_medium`);
  lines.push(`    size: 16`);
  lines.push(`  - file: "gfonts://Share Tech Mono"`);
  lines.push(`    id: font_large`);
  lines.push(`    size: 24`);
  lines.push(``);

  // Extract entity bindings
  // (We'll still keep the extraction logic if needed for other things, but remove YAML output)
  // const bindings = extractAllBindings(project);

  // Globals for page navigation
  lines.push(`globals:`);
  lines.push(`  - id: current_page`);
  lines.push(`    type: int`);
  lines.push(`    initial_value: "0"`);
  lines.push(`  - id: scroll_y`);
  lines.push(`    type: int`);
  lines.push(`    initial_value: "0"`);
  lines.push(`  - id: max_scroll_y`);
  lines.push(`    type: int`);
  lines.push(`    initial_value: "0"`);
  lines.push(``);

  // Interval for touch polling
  lines.push(`interval:`);
  lines.push(`  - interval: 16ms`);
  lines.push(`    then:`);
  lines.push(`      - lambda: |-`);
  lines.push(`          id(main_display).update();`);
  lines.push(``);

  // Page count info
  lines.push(`# Total dashboard pages: ${project.dashboardPages.length}`);
  for (let i = 0; i < project.dashboardPages.length; i++) {
    lines.push(`# Page ${i}: ${project.dashboardPages[i].name}`);
  }

  return lines.join("\n");
}

interface BindingResult {
  sensors: string[];
  textSensors: string[];
  actions: string[];
}

function extractAllBindings(project: Project): BindingResult {
  const sensors = new Set<string>();
  const textSensors = new Set<string>();
  const actions = new Set<string>();

  // Extract from dashboard pages
  for (const page of project.dashboardPages || []) {
    for (const comp of page.components) {
      extractComponentBindings(comp, sensors, textSensors, actions);
    }
  }

  // Extract from detail views
  for (const view of project.detailViews || []) {
    for (const comp of view.components) {
      extractComponentBindings(comp, sensors, textSensors, actions);
    }
  }

  return {
    sensors: [...sensors],
    textSensors: [...textSensors],
    actions: [...actions],
  };
}

function extractComponentBindings(
  comp: any,
  sensors: Set<string>,
  textSensors: Set<string>,
  actions: Set<string>
) {
  // Value bindings (slider, gauge)
  if ("valueBinding" in comp && comp.valueBinding) {
    const entity = (comp.valueBinding as { entityId: string }).entityId;
    if (isNumericDomain(entity)) {
      sensors.add(entity);
    } else {
      textSensors.add(entity);
    }
  }

  // Text bindings
  if ("textBinding" in comp && comp.textBinding) {
    const entity = (comp.textBinding as { entityId: string }).entityId;
    textSensors.add(entity);
  }

  // Action bindings
  if ("pressAction" in comp && comp.pressAction) {
    const service = (comp.pressAction as { service: string }).service;
    actions.add(service);
  }
  if ("holdAction" in comp && comp.holdAction) {
    const service = (comp.holdAction as { service: string }).service;
    actions.add(service);
  }
}

function isNumericDomain(entityId: string): boolean {
  const domain = entityId.split(".")[0];
  return [
    "sensor",
    "input_number",
    "number",
    "counter",
    "climate",
  ].includes(domain);
}

function entityToId(entity: string): string {
  return "ha_" + entity.replace(/\./g, "_");
}

export { entityToId };
