/**
 * Initial Flash YAML Generator
 *
 * Generates the ESPHome configuration for first-time device setup.
 * This firmware creates a WiFi hotspot with captive portal for configuration,
 * and includes OTA update capability to pull the full dashboard firmware later.
 */

/**
 * Generate the initial flash YAML configuration.
 * @param deviceName - The device name (used for AP SSID and ESPHome name)
 * @returns The complete ESPHome YAML configuration
 */
export function generateInitialFlashYAML(deviceName: string): string {
  // Sanitize device name for ESPHome (lowercase, hyphens)
  const safeName = deviceName
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");

  const friendlyName = deviceName;

  return `# ============================================
# Initial Flash Firmware
# Generated by ESPHome Designer
# ============================================
# This firmware is for first-time device setup.
# It creates a WiFi hotspot for configuration and
# will automatically update to the full dashboard
# firmware once connected to your network.

substitutions:
  device_name: ${safeName}
  friendly_name: "${friendlyName}"

esphome:
  name: \${device_name}
  friendly_name: \${friendly_name}
  on_boot:
    priority: 800
    then:
      - logger.log: "Starting initial setup firmware"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal

wifi:
  ap:
    ssid: "\${device_name} Setup"

captive_portal:

# Improv WiFi for easy provisioning via BLE
esp32_improv:
  authorizer: none

logger:

api:
  reboot_timeout: 15min

ota:
  - platform: esphome
  - platform: http_request

http_request:

update:
  - platform: http_request
    name: Firmware
    source: !secret firmware_update_url

time:
  - platform: sntp
    id: sntp_time

# ============================================
# Hardware Configuration
# Guition ESP32-S3-4848S040 (4.0" 480x480)
# ============================================

i2c:
  id: touch_i2c
  frequency: 400kHz
  sda: GPIO19
  scl:
    number: GPIO45
    ignore_strapping_warning: true

touchscreen:
  platform: gt911
  id: touch_gt911
  i2c_id: touch_i2c
  display: main_display

spi:
  id: lcd_spi
  clk_pin: GPIO48
  mosi_pin: GPIO47

output:
  - platform: ledc
    pin: GPIO38
    frequency: 150Hz
    id: backlight_pwm
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 1s
    initial_state:
      brightness: 100%

display:
  - platform: st7701s
    id: main_display
    dimensions:
      width: 480
      height: 480
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: false
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 14MHz
    pclk_inverted: false
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 50
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 20
    update_interval: never
    auto_clear_enabled: false
    init_sequence:
      # PAGE0
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xC0, 0x3B, 0x00]
      - [0xC1, 0x0D, 0x02]
      - [0xC2, 0x31, 0x05]
      - [0xCD, 0x00]
      # Positive Voltage Gamma
      - [0xB0, 0x00, 0x11, 0x18, 0x0E, 0x11, 0x06, 0x07, 0x08, 0x07, 0x22, 0x04, 0x12, 0x0F, 0xAA, 0x31, 0x18]
      # Negative Voltage Gamma
      - [0xB1, 0x00, 0x11, 0x19, 0x0E, 0x12, 0x07, 0x08, 0x08, 0x08, 0x22, 0x04, 0x11, 0x11, 0xA9, 0x32, 0x18]
      # PAGE1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x11]
      - [0xB0, 0x60]
      - [0xB1, 0x32]
      - [0xB2, 0x07]
      - [0xB3, 0x80]
      - [0xB5, 0x49]
      - [0xB7, 0x85]
      - [0xB8, 0x21]
      - [0xC1, 0x78]
      - [0xC2, 0x78]
      - [0xE0, 0x00, 0x1B, 0x02]
      - [0xE1, 0x08, 0xA0, 0x00, 0x00, 0x07, 0xA0, 0x00, 0x00, 0x00, 0x44, 0x44]
      - [0xE2, 0x11, 0x11, 0x44, 0x44, 0xED, 0xA0, 0x00, 0x00, 0xEC, 0xA0, 0x00, 0x00]
      - [0xE3, 0x00, 0x00, 0x11, 0x11]
      - [0xE4, 0x44, 0x44]
      - [0xE5, 0x0A, 0xE9, 0xD8, 0xA0, 0x0C, 0xEB, 0xD8, 0xA0, 0x0E, 0xED, 0xD8, 0xA0, 0x10, 0xEF, 0xD8, 0xA0]
      - [0xE6, 0x00, 0x00, 0x11, 0x11]
      - [0xE7, 0x44, 0x44]
      - [0xE8, 0x09, 0xE8, 0xD8, 0xA0, 0x0B, 0xEA, 0xD8, 0xA0, 0x0D, 0xEC, 0xD8, 0xA0, 0x0F, 0xEE, 0xD8, 0xA0]
      - [0xEB, 0x02, 0x00, 0xE4, 0xE4, 0x88, 0x00, 0x40]
      - [0xEC, 0x3C, 0x00]
      - [0xED, 0xAB, 0x89, 0x76, 0x54, 0x02, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x20, 0x45, 0x67, 0x98, 0xBA]
      # VAP & VAN
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xE5, 0xE4]
      # PAGE0
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0x3A, 0x60]  # RGB666
      - delay 10ms
      - [0x11]  # Sleep Out
      - delay 120ms
      - [0x29]  # Display On
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

# Setup instructions displayed on first boot
lvgl:
  id: my_lvgl
  disp_bg_color: 0x000000
  buffer_size: 100%
  touchscreens:
    - touch_gt911
  pages:
    - id: setup_page
      bg_color: 0x0B1020
      widgets:
        - label:
            text: "Wi-Fi Setup"
            align: TOP_MID
            y: 24
            text_color: 0xFFFFFF
            text_font: montserrat_48

        - label:
            text: "1. Connect to the hotspot\\n2. Open the captive portal\\n3. Enter your Wi-Fi details"
            align: CENTER
            text_align: CENTER
            text_color: 0xD7E3FF
            text_font: montserrat_24

        - label:
            text: "Network: \${device_name} Setup\\nPassword: none (open network)"
            align: BOTTOM_MID
            y: -30
            text_align: CENTER
            text_color: 0x88A4FF
            text_font: montserrat_20
`;
}
