import type { Project, Page, Component } from "@esphome-designer/schema";

export function generateRenderPages(project: Project): string {
   const lines: string[] = [];

   lines.push(`/**`);
   lines.push(` * AUTO-GENERATED by ESPHome Designer - Dashboard Pages`);
   lines.push(` * Project: ${project.name}`);
   lines.push(` * Generated: ${new Date().toISOString()}`);
   lines.push(` */`);
   lines.push(``);
   lines.push(`#pragma once`);
   lines.push(`#include "esphome.h"`);
   lines.push(`#include "state_manager.h"`);
   lines.push(`#include "render_helpers.h"`);
   lines.push(``);
   
   lines.push(`// Forward declarations for ESPHome-generated fonts`);
   lines.push(`extern esphome::font::Font *font_tiny;`);
   lines.push(`extern esphome::font::Font *font_small;`);
   lines.push(`extern esphome::font::Font *font_medium;`);
   lines.push(`extern esphome::font::Font *font_large;`);
   lines.push(``);

   // Generate page render functions
   for (let i = 0; i < project.dashboardPages.length; i++) {
     const page = project.dashboardPages[i];
     lines.push(generatePageRenderer(page, i));
     lines.push(``);
   }

   return lines.join("\n");
 }

function generatePageRenderer(page: Page, index: number): string {
   const lines: string[] = [];

   lines.push(`void renderPage${index}(display::Display& it) {`);
   lines.push(`  // Dashboard Page ${index}: ${page.name}`);

   if (page.backgroundColor) {
     lines.push(`  it.fill(${colorToCpp(page.backgroundColor)});`);
   }

   // Render all components on this page
   if (page.components.length === 0) {
     lines.push(`  // (No components defined for this page)`);
   } else {
     for (const comp of page.components) {
       lines.push(generateComponentCode(comp));
     }
   }

   lines.push(`}`);
   return lines.join("\n");
 }

function generateComponentCode(comp: Component): string {
   switch (comp.type) {
     case "text":
       return generateTextCode(comp);
     case "button":
       return generateButtonCode(comp);
     case "container":
       return generateContainerCode(comp);
     default:
       return `  // Unsupported component type for pages: ${comp.type}`;
   }
 }

function generateTextCode(comp: any): string {
   const color = comp.color ? `Color(${comp.color.r}, ${comp.color.g}, ${comp.color.b})` : "Theme::FOREGROUND";
   const font = comp.fontSize === "small" ? "font_small" : comp.fontSize === "large" ? "font_large" : "font_medium";

   if (comp.textBinding) {
     const stateVar = `gState.${comp.textBinding.entityId.replace(/\./g, "_")}`;
     return `  // Text: ${comp.id} (bound to ${comp.textBinding.entityId})
   it.printf(${comp.position.x}, ${comp.position.y}, ${font}, ${color}, "${comp.text ?? ""}");`;
   }

   return `  // Text: ${comp.id}
   it.print(${comp.position.x}, ${comp.position.y}, ${font}, ${color}, "${comp.text ?? ""}");`;
 }

function generateButtonCode(comp: any): string {
   const bgColor = comp.backgroundColor ? `Color(${comp.backgroundColor.r}, ${comp.backgroundColor.g}, ${comp.backgroundColor.b})` : "Theme::BACKGROUND_SECONDARY";
   const x = comp.position.x;
   const y = comp.position.y;
   const w = comp.size.width;
   const h = comp.size.height;

   return `  // Button: ${comp.id}
   it.filled_rectangle(${x}, ${y}, ${w}, ${h}, ${bgColor});
   it.rectangle(${x}, ${y}, ${w}, ${h}, Theme::ACCENT);
   it.printf(${x} + ${w}/2, ${y} + ${h}/2, font_medium, Theme::FOREGROUND, TextAlign::CENTER, "${comp.label ?? ""}");`;
 }

function generateContainerCode(comp: any): string {
   const label = (comp as any).label || "";
   return `  // Container: ${comp.id}
   drawThemedBox(it, ${comp.position.x}, ${comp.position.y}, ${comp.size.width}, ${comp.size.height}, "${label}");`;
 }

function colorToCpp(c: any): string {
   return `Color(${c.r}, ${c.g}, ${c.b})`;
 }

function entityToId(entity: string): string {
   return "ha_" + entity.replace(/\./g, "_");
 }