import type { Project, DetailView } from "@esphome-designer/schema";

export function generateRenderDetails(project: Project): string {
   const lines: string[] = [];

   lines.push(`/**`);
   lines.push(` * AUTO-GENERATED by ESPHome Designer - Detail Views`);
   lines.push(` * Project: ${project.name}`);
   lines.push(` * Generated: ${new Date().toISOString()}`);
   lines.push(` */`);
   lines.push(``);
   lines.push(`#pragma once`);
   lines.push(`#include "esphome.h"`);
   lines.push(`#include "state_manager.h"`);
   lines.push(`#include "render_helpers.h"`);
   lines.push(``);
   
   lines.push(`// Forward declarations for ESPHome-generated fonts`);
   lines.push(`extern esphome::font::Font *font_tiny;`);
   lines.push(`extern esphome::font::Font *font_small;`);
   lines.push(`extern esphome::font::Font *font_medium;`);
   lines.push(`extern esphome::font::Font *font_large;`);
   lines.push(``);

   const detailViews = project.detailViews || [];

   // Generate individual detail view rendering functions
   for (const view of detailViews) {
     lines.push(generateDetailViewFunction(view));
     lines.push(``);
   }

   return lines.join("\n");
 }

 function generateDetailViewFunction(view: DetailView): string {
   const lines: string[] = [];
   const safeId = view.id.toUpperCase().replace(/-/g, '_');
   
   lines.push(`void renderDetail_${safeId}(display::Display& it) {`);
   lines.push(`  // Detail View: ${view.title}`);
   lines.push(`  // Virtual height: ${view.height}px`);
   const headerHeight = view.headerHeight ?? 45;
   lines.push(`  // Max scroll: ${view.height - headerHeight}px`);
   lines.push(``);
   
   // Components rendering with scroll offset
   lines.push(`  int logicalY = ${headerHeight};  // Start below header`);
   lines.push(`  auto getSY = [&](int ly) { return ly + gState.scrollY; };`);
   lines.push(``);
   
   // Generate component rendering code
   if (view.components.length > 0) {
     lines.push(`  // Render ${view.components.length} component(s)`);
     for (const comp of view.components) {
       lines.push(`  // TODO: Component: ${comp.id} (${comp.type}) at position (${comp.position.x}, ${comp.position.y})`);
     }
   } else {
     lines.push(`  // (No components defined for this detail view)`);
   }
   
   lines.push(``);
   lines.push(`  // Draw detail header last (always on top)`);
   lines.push(`  drawDetailHeader(it, "${view.title.toUpperCase()}");`);
   
   lines.push(`}`);
   
   return lines.join("\n");
 }