/**
 * ESPHome Secrets YAML Generator
 *
 * Generates a secrets.yaml file with the firmware update URL.
 */

import type { Project } from "@esphome-designer/schema";
import { escapeYAMLDoubleQuoted } from "./utils";
import { isScreenshotDebugEnabled, screenshotUploadUrl } from "./screenshot-feature";

interface GenerateSecretsOptions {
  includeOtaSecrets?: boolean;
}

function manifestUrlFor(firmwareUrl: string): string {
  return `${firmwareUrl.replace(/\/$/, "")}/manifest`;
}

export function generateSecretsYAML(project: Project, options: GenerateSecretsOptions = {}): string {
  const lines: string[] = [];
  const firmwareUpdateUrl = project.secrets?.firmwareUpdateUrl ?? "http://YOUR_SERVER/api/firmware/YOUR_TOKEN";
  const includeOtaSecrets = options.includeOtaSecrets ?? true;

  lines.push(`# ============================================`);
  lines.push(`# ESPHome Secrets`);
  lines.push(`# Generated by ESPHome Designer`);
  lines.push(`# ============================================`);
  lines.push(``);

  if (includeOtaSecrets) {
    // Firmware update URL (for OTA via HTTP)
    lines.push(`# Firmware Update URL (auto-populated when project is published)`);
    lines.push(`firmware_update_url: "${escapeYAMLDoubleQuoted(firmwareUpdateUrl)}"`);
    lines.push(`firmware_manifest_url: "${escapeYAMLDoubleQuoted(manifestUrlFor(firmwareUpdateUrl))}"`);
  }

  if (project.secrets?.homeAssistantBaseUrl) {
    lines.push(``);
    lines.push(`# Home Assistant base URL for resolving relative entity_picture paths`);
    lines.push(`home_assistant_base_url: "${escapeYAMLDoubleQuoted(project.secrets.homeAssistantBaseUrl)}"`);
  }

  if (isScreenshotDebugEnabled() && screenshotUploadUrl()) {
    lines.push(``);
    lines.push(`# Screenshot upload URL (debug feature, gated by SCREENSHOT_DEBUG_ENABLED env)`);
    lines.push(`screenshot_upload_url: "${escapeYAMLDoubleQuoted(screenshotUploadUrl()!)}"`);
  }

  return lines.join("\n");
}
