/**
 * ESPHome Secrets YAML Generator
 *
 * Generates a secrets.yaml file with the firmware update URL.
 */

import type { Project } from "@esphome-designer/schema";

function manifestUrlFor(firmwareUrl: string): string {
  return `${firmwareUrl.replace(/\/$/, "")}/manifest`;
}

export function generateSecretsYAML(project: Project): string {
  const lines: string[] = [];
  const firmwareUpdateUrl = project.secrets?.firmwareUpdateUrl ?? "http://YOUR_SERVER/api/firmware/YOUR_TOKEN";

  lines.push(`# ============================================`);
  lines.push(`# ESPHome Secrets`);
  lines.push(`# Generated by ESPHome Designer`);
  lines.push(`# ============================================`);
  lines.push(``);

  // Firmware update URL (for OTA via HTTP)
  lines.push(`# Firmware Update URL (auto-populated when project is published)`);
  lines.push(`firmware_update_url: "${firmwareUpdateUrl}"`);
  lines.push(`firmware_manifest_url: "${manifestUrlFor(firmwareUpdateUrl)}"`);

  if (project.secrets?.homeAssistantBaseUrl) {
    lines.push(``);
    lines.push(`# Home Assistant base URL for resolving relative entity_picture paths`);
    lines.push(`home_assistant_base_url: "${project.secrets.homeAssistantBaseUrl}"`);
  }

  return lines.join("\n");
}


