/**
 * ESPHome Secrets YAML Generator
 *
 * Generates a secrets.yaml file with the firmware update URL.
 */

import type { Project } from "@esphome-designer/schema";

export function generateSecretsYAML(project: Project): string {
  const lines: string[] = [];

  lines.push(`# ============================================`);
  lines.push(`# ESPHome Secrets`);
  lines.push(`# Generated by ESPHome Designer`);
  lines.push(`# ============================================`);
  lines.push(``);

  // Firmware update URL (for OTA via HTTP)
  lines.push(`# Firmware Update URL (auto-populated when project is published)`);
  lines.push(`firmware_update_url: "${project.secrets?.firmwareUpdateUrl ?? "http://YOUR_SERVER/api/firmware/YOUR_TOKEN/manifest"}"`);
  lines.push(``);
  lines.push(`# Home Assistant base URL for resolving relative entity_picture paths`);
  lines.push(`home_assistant_base_url: "${project.secrets?.homeAssistantBaseUrl ?? "http://homeassistant.local:8123"}"`);

  return lines.join("\n");
}

/**
 * Check if project has any secrets configured
 */
export function hasSecrets(project: Project): boolean {
  return !!(
    project.secrets?.firmwareUpdateUrl ||
    project.secrets?.homeAssistantBaseUrl
  );
}
