import type { Project, StateField } from "@esphome-designer/schema";

export function generateSensorsYAML(project: Project): string {
  const fields = project.state?.fields ?? [];
  const sensors: StateField[] = [];
  const textSensors: StateField[] = [];

  // Partition by type
  for (const field of fields) {
    if (field.cppType === "std::string") {
      textSensors.push(field);
    } else {
      sensors.push(field);
    }
  }

  const lines: string[] = [];
   lines.push(`# AUTO-GENERATED by ESPHome Designer`);
   lines.push(`# Project: ${project.name}`);
   lines.push(`# Generated: ${new Date().toISOString()}`);
   lines.push(`# DO NOT EDIT - regenerate from editor`);
   lines.push(``);

   // Touchscreen sensor via I2C
   lines.push(`# Touchscreen coordinates (raw I2C readings)`);
   lines.push(`sensor:`);
   lines.push(`  - platform: template`);
   lines.push(`    id: touch_x_raw`);
   lines.push(`    internal: true`);
   lines.push(`  - platform: template`);
   lines.push(`    id: touch_y_raw`);
   lines.push(`    internal: true`);
   lines.push(`  - platform: template`);
   lines.push(`    id: touch_status`);
   lines.push(`    internal: true`);
   lines.push(``);

   // Numeric sensors from Home Assistant
   if (sensors.length > 0) {
     for (const field of sensors) {
       lines.push(`  - platform: homeassistant`);
       lines.push(`    id: ha_sensor_${field.name}`);
       lines.push(`    entity_id: ${field.haEntity}`);
       lines.push(`    internal: true`);
       lines.push(`    filters:`);
       lines.push(`      - lambda: "return isnan(x) ? 0 : x;"`);
       lines.push(`    on_value:`);
       lines.push(`      - lambda: "gState.${field.name} = x;"`);
       lines.push(``);
     }
   }

   // Text sensors
   if (textSensors.length > 0) {
     lines.push(`text_sensor:`);
     for (const field of textSensors) {
       lines.push(`  - platform: homeassistant`);
       lines.push(`    id: ha_text_${field.name}`);
       lines.push(`    entity_id: ${field.haEntity}`);
       lines.push(`    internal: true`);
       lines.push(`    on_value:`);
       lines.push(`      - lambda: "gState.${field.name} = x;"`);
       lines.push(``);
     }
   }

   // Touchscreen I2C parsing
   lines.push(`# Touchscreen I2C register reading`);
   lines.push(`binary_sensor:`);
   lines.push(`  - platform: template`);
   lines.push(`    id: touch_detected`);
   lines.push(`    internal: true`);
   lines.push(`    lambda: 'return false;'`);
   lines.push(`    on_press:`);
   lines.push(`      - lambda: |-`);
   lines.push(`          // Touch pressed - handled in main rendering loop`);
   lines.push(``);

   return lines.join("\n");
}
