/**
 * State Manager Generator for ESPHome Designer
 * 
 * Generates state_manager.h from project schema.
 * This includes:
 * - ViewState enum (DASHBOARD + all detail views)
 * - Scroll constants for each detail view
 * - DisplayState struct with navigation and sensor fields
 * - Global gState instance
 * - Theme color constants
 * 
 * See: PHASE_2.md
 */

import type { Project, DetailView, StateField, Color } from "@esphome-designer/schema";

export interface GeneratedState {
  enumDefinition: string;
  structDefinition: string;
  scrollConstants: string;
  themeColors: string;
}

/**
 * Main generation function. Discovers detail views, generates enum, constants, and struct.
 */
export function generateStateManager(project: Project): GeneratedState {
  // Step 1: Discover all detail views
  const detailViews = discoverDetailViews(project);
  const viewStateEnum = generateViewStateEnum(detailViews);

  // Step 2: Generate scroll constants
  const scrollConstants = generateScrollConstants(detailViews);

  // Step 3: Generate DisplayState struct (with numPages from project)
  const numPages = project.dashboardPages?.length ?? 0;
  const structDefinition = generateDisplayStateStruct(
    project.state?.fields ?? [],
    detailViews,
    numPages
  );

  // Step 4: Generate theme colors
  const themeColors = generateThemeColors(project);

  return {
    enumDefinition: viewStateEnum,
    structDefinition,
    scrollConstants,
    themeColors,
  };
}

/**
 * Generates complete state_manager.h header file content
 */
export function generateStateHeader(project: Project): string {
  const generated = generateStateManager(project);

  const lines: string[] = [];
  
  lines.push(`#pragma once`);
  lines.push(`#include "esphome.h"`);
  lines.push(``);
  lines.push(`// AUTO-GENERATED by ESPHome Designer`);
  lines.push(`// Project: ${project.name}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`// DO NOT EDIT - regenerate from editor`);
  lines.push(``);
  lines.push(generated.enumDefinition);
  lines.push(``);
  lines.push(generated.scrollConstants);
  lines.push(``);
  lines.push(generated.structDefinition);
  lines.push(``);
   lines.push(`// Global state instance`);
   lines.push(`DisplayState gState;`);
   lines.push(``);
   lines.push(generated.themeColors);
   lines.push(``);
   
   // Add navigation function declarations
   lines.push(`// Navigation function declarations`);
   lines.push(`void openView(ViewState view) {`);
   lines.push(`  gState.currentView = view;`);
   lines.push(`  gState.scrollY = 0;`);
   lines.push(`}`);
   lines.push(``);
   lines.push(`void goBack() {`);
   lines.push(`  gState.currentView = VIEW_MAIN_DASHBOARD;`);
   lines.push(`  gState.scrollY = 0;`);
   lines.push(`}`);
   lines.push(``);
   lines.push(`void nextPage() {`);
   lines.push(`  if (gState.currentView == VIEW_MAIN_DASHBOARD) {`);
   lines.push(`    gState.mainPageIndex = (gState.mainPageIndex + 1) % ${project.dashboardPages?.length ?? 1};`);
   lines.push(`  }`);
   lines.push(`}`);
   lines.push(``);
   lines.push(`void prevPage() {`);
   lines.push(`  if (gState.currentView == VIEW_MAIN_DASHBOARD) {`);
   lines.push(`    gState.mainPageIndex = (gState.mainPageIndex - 1 + ${project.dashboardPages?.length ?? 1}) % ${project.dashboardPages?.length ?? 1};`);
   lines.push(`  }`);
   lines.push(`}`);

   return lines.join("\n");
 }

/**
 * Discovers all detail views across the project.
 * Validates that IDs are unique and match the pattern.
 * 
 * @throws Error if duplicate IDs found or invalid format
 */
function discoverDetailViews(project: Project): DetailView[] {
  const views: DetailView[] = [];
  const seen = new Set<string>();

  // Check detailViews at project level
  if (project.detailViews) {
    for (const detail of project.detailViews) {
      validateDetailViewId(detail.id);
      
      if (seen.has(detail.id)) {
        throw new Error(
          `Duplicate detail view ID: ${detail.id} (must be unique across all pages)`
        );
      }
      seen.add(detail.id);
      views.push(detail);
    }
  }

  return views;
}

/**
 * Validates that a detail view ID matches UPPER_SNAKE_CASE pattern
 */
function validateDetailViewId(id: string): void {
  if (!/^[A-Z0-9_]+$/.test(id)) {
    throw new Error(
      `Invalid detail view ID: ${id} (must be UPPER_SNAKE_CASE like TEMPS, VACUUM, etc.)`
    );
  }
}

/**
 * Generates the ViewState enum with DASHBOARD and all detail views
 */
function generateViewStateEnum(views: DetailView[]): string {
  const lines: string[] = [];

  if (views.length > 0) {
    lines.push("// View IDs: " + views.map(v => `${v.id} -> VIEW_DETAIL_${v.id}`).join(", "));
  }
  
  lines.push("enum ViewState {");
  lines.push("  VIEW_MAIN_DASHBOARD = 0,");

  views.forEach((view, idx) => {
    // Prepend VIEW_DETAIL_ prefix to short ID
    lines.push(`  VIEW_DETAIL_${view.id} = ${idx + 1},`);
  });

  lines.push("};");

  return lines.join("\n");
}

/**
 * Generates scroll bound constants for each detail view
 */
function generateScrollConstants(views: DetailView[]): string {
  const lines: string[] = [];

  lines.push("// Navigation constants");
  lines.push("const int DISPLAY_WIDTH = 240;");
  lines.push("const int DISPLAY_HEIGHT = 320;");
  lines.push("const int DEFAULT_HEADER_HEIGHT = 45;");

  if (views.length > 0) {
    lines.push("");
    lines.push("// Scroll bounds for detail views (height - headerHeight)");
    
    views.forEach((view) => {
      const headerHeight = view.headerHeight ?? 45;
      const maxScroll = view.height - headerHeight;
      const viewEnumName = `VIEW_DETAIL_${view.id}`;
      lines.push(`const int SCROLL_Y_MAX_${viewEnumName} = ${maxScroll};  // ${view.height} - ${headerHeight}`);
    });
  }

  return lines.join("\n");
}

/**
 * Generates the DisplayState struct with navigation and sensor fields
 */
function generateDisplayStateStruct(
  fields: StateField[],
  views: DetailView[],
  numPages: number
): string {
  const lines: string[] = [];

  lines.push("// Global display state");
  lines.push("struct DisplayState {");
  lines.push("  // Navigation");
  lines.push("  int mainPageIndex = 0;");
  lines.push(`  int numPages = ${numPages};`);
  lines.push("  ViewState currentView = VIEW_MAIN_DASHBOARD;");
  lines.push("  int scrollY = 0;");
  lines.push("  int maxScrollY = 0;");
  lines.push("");

  if (fields.length > 0) {
    lines.push("  // Sensor fields");
    for (const field of fields) {
      const defaultVal = formatDefaultValue(field.cppType, field.defaultValue);
      lines.push(`  ${field.cppType} ${field.name} = ${defaultVal};`);
    }
    lines.push("");
  }

  lines.push("  // Helper: check if we're in the main dashboard");
  lines.push("  bool isDashboard() const {");
  lines.push("    return currentView == VIEW_MAIN_DASHBOARD;");
  lines.push("  }");
  lines.push("");

  lines.push("  // Update scroll bounds based on current view");
  lines.push("  void updateScrollBounds() {");
  
  if (views.length > 0) {
    lines.push("    switch (currentView) {");
    views.forEach((view) => {
      const viewEnumName = `VIEW_DETAIL_${view.id}`;
      lines.push(`      case ${viewEnumName}:`);
      lines.push(`        maxScrollY = SCROLL_Y_MAX_${viewEnumName};`);
      lines.push(`        break;`);
    });
    lines.push("      default:");
    lines.push("        maxScrollY = 0;");
    lines.push("    }");
  } else {
    lines.push("    maxScrollY = 0;");
  }
  
  lines.push("  }");
  lines.push("};");

  return lines.join("\n");
}

/**
 * Formats default values according to C++ type requirements
 */
function formatDefaultValue(cppType: string, value: any): string {
  if (cppType === "std::string") {
    if (value === undefined || value === null || value === "") {
      return '""';
    }
    // Escape quotes in string values
    return `"${String(value).replace(/"/g, '\\"')}"`;
  }
  
  if (cppType === "bool") {
    return value ? "true" : "false";
  }
  
  if (value === undefined || value === null) {
    return cppType === "float" ? "0.0f" : "0";
  }
  
  // For floats, ensure we have decimal point
  if (cppType === "float") {
    const numValue = Number(value);
    // If it's a whole number, add .0
    if (Number.isInteger(numValue)) {
      return `${numValue}.0f`;
    }
    return `${numValue}f`;
  }
  
  return String(value);
}

/**
 * Generates theme color constants
 */
function generateThemeColors(project: Project): string {
  const lines: string[] = [];

  if (!project.theme) {
    return "// No theme defined";
  }

  lines.push("// Theme colors");
  lines.push("namespace Theme {");
  
  for (const [key, color] of Object.entries(project.theme.colors)) {
    const colorName = key.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '');
    lines.push(`  const Color ${colorName} = ${colorToCpp(color as Color)};`);
  }
  
  lines.push("}");

  return lines.join("\n");
}

/**
 * Converts Color object to C++ Color constructor
 */
function colorToCpp(c: Color): string {
  return `Color(${c.r}, ${c.g}, ${c.b})`;
}
