import type { Project, Component, ActionBinding, DetailView, Page } from "@esphome-designer/schema";

interface HitBoxDef {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  pageIndex?: number;
  viewId?: string;
  action: ActionDef;
}

interface ActionDef {
  type: "OPEN_DETAIL" | "GO_BACK" | "NEXT_PAGE" | "PREV_PAGE" | "SERVICE_CALL";
  targetView?: string;
  service?: string;
  entityId?: string;
  dataJson?: string;
}

export function generateTouchHandler(project: Project): string {
  const hitBoxes: HitBoxDef[] = [];

  // 1. Dashboard Page Hitboxes
  project.dashboardPages.forEach((page, pageIndex) => {
    page.components.forEach(comp => {
      collectHitBoxes(comp, hitBoxes, { pageIndex });
    });
  });

  // 2. Detail View Hitboxes
  project.detailViews.forEach(view => {
    view.components.forEach(comp => {
      collectHitBoxes(comp, hitBoxes, { viewId: view.id });
    });
  });

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by ESPHome Designer`);
  lines.push(`#pragma once`);
  lines.push(`#include "esphome.h"`);
  lines.push(`#include "state_manager.h"`);
  lines.push(``);

  lines.push(`enum ActionType {`);
  lines.push(`  ACTION_OPEN_DETAIL,`);
  lines.push(`  ACTION_GO_BACK,`);
  lines.push(`  ACTION_NEXT_PAGE,`);
  lines.push(`  ACTION_PREV_PAGE,`);
  lines.push(`  ACTION_SERVICE_CALL,`);
  lines.push(`};`);
  lines.push(``);

  lines.push(`struct HitBox {`);
  lines.push(`  const char* id;`);
  lines.push(`  int x, y, w, h;`);
  lines.push(`  ActionType type;`);
  lines.push(`  union {`);
  lines.push(`    ViewState targetView;`);
  lines.push(`    struct {`);
  lines.push(`      const char* service;`);
  lines.push(`      const char* entityId;`);
  lines.push(`      const char* dataJson;`);
  lines.push(`    } serviceCall;`);
  lines.push(`  } action;`);
  lines.push(`};`);
  lines.push(``);

  // Helper function to generate individual HitBox initialization
  const genHitBox = (hb: HitBoxDef) => {
    const lines: string[] = [];
    lines.push(`  {`);
    lines.push(`    .id = "${hb.id}",`);
    lines.push(`    .x = ${hb.x}, .y = ${hb.y}, .w = ${hb.w}, .h = ${hb.h},`);
    lines.push(`    .type = ${actionTypeToEnum(hb.action.type)},`);
    if (hb.action.type === "SERVICE_CALL") {
      lines.push(`    .action = { .serviceCall = {`);
      lines.push(`      .service = "${hb.action.service}",`);
      lines.push(`      .entityId = "${hb.action.entityId}",`);
      lines.push(`      .dataJson = "${escapeJson(hb.action.dataJson || "{}")}",`);
      lines.push(`    }},`);
    } else if (hb.action.type === "OPEN_DETAIL") {
      lines.push(`    .action = { .targetView = VIEW_DETAIL_${hb.action.targetView?.toUpperCase().replace(/-/g, '_')} },`);
    }
    lines.push(`  }`);
    return lines.join("\n");
  };

  // Generate arrays for each page
  project.dashboardPages.forEach((page, i) => {
    const pageBoxes = hitBoxes.filter(hb => hb.pageIndex === i);
    lines.push(`const HitBox HIT_BOXES_PAGE_${i}[] = {`);
    lines.push(pageBoxes.map(genHitBox).join(",\n"));
    lines.push(`};`);
    lines.push(`const int HIT_BOX_COUNT_PAGE_${i} = ${pageBoxes.length};`);
    lines.push(``);
  });

  // Generate arrays for each detail view
  project.detailViews.forEach(view => {
    const safeId = view.id.toUpperCase().replace(/-/g, '_');
    const viewBoxes = hitBoxes.filter(hb => hb.viewId === view.id);
    lines.push(`const HitBox HIT_BOXES_VIEW_${safeId}[] = {`);
    lines.push(viewBoxes.map(genHitBox).join(",\n"));
    lines.push(`};`);
    lines.push(`const int HIT_BOX_COUNT_VIEW_${safeId} = ${viewBoxes.length};`);
    lines.push(``);
  });

  lines.push(`void dispatchAction(const HitBox& box) {`);
  lines.push(`  switch (box.type) {`);
  lines.push(`    case ACTION_OPEN_DETAIL:`);
  lines.push(`      openView(box.action.targetView);`);
  lines.push(`      break;`);
  lines.push(`    case ACTION_GO_BACK:`);
  lines.push(`      goBack();`);
  lines.push(`      break;`);
  lines.push(`    case ACTION_NEXT_PAGE:`);
  lines.push(`      nextPage();`);
  lines.push(`      break;`);
  lines.push(`    case ACTION_PREV_PAGE:`);
  lines.push(`      prevPage();`);
  lines.push(`      break;`);
   lines.push(`    case ACTION_SERVICE_CALL:`);
   lines.push(`      // TODO: Implement Home Assistant service call`);
   lines.push(`      // Service: ${'' /* placeholder */} Entity: ${'' /* placeholder */}`);
   lines.push(`      // This requires ESPHome Home Assistant API integration`);
   lines.push(`      break;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`class TouchHandler {`);
  lines.push(` public:`);
  lines.push(`  static void handleTouch(float x, float y, bool touched) {`);
  lines.push(`    static bool was_touched = false;`);
  lines.push(`    static float start_x = 0;`);
  lines.push(`    static float start_y = 0;`);
  lines.push(`    static float last_y = 0;`);
  lines.push(``);
  lines.push(`    if (touched && !was_touched) {`);
  lines.push(`      start_x = x;`);
  lines.push(`      start_y = y;`);
  lines.push(`      last_y = y;`);
  lines.push(`    } else if (!touched && was_touched) {`);
  lines.push(`      float dx = x - start_x;`);
  lines.push(`      float dy = y - start_y;`);
  lines.push(``);
   lines.push(`      if (gState.currentView == VIEW_MAIN_DASHBOARD) {`);
   lines.push(`        if (dx > 40) { // Prev page`);
   lines.push(`          prevPage();`);
   lines.push(`        } else if (dx < -40) { // Next page`);
   lines.push(`          nextPage();`);
   lines.push(`        } else if (abs(dx) < 10 && abs(dy) < 10) {`);
   lines.push(`          handleTap(x, y);`);
   lines.push(`        }`);
   lines.push(`      } else {`);
   lines.push(`        if (abs(dx) < 10 && abs(dy) < 10) {`);
   lines.push(`          handleTap(x, y);`);
   lines.push(`        }`);
   lines.push(`      }`);
   lines.push(`    } else if (touched && was_touched && gState.currentView != VIEW_MAIN_DASHBOARD) {`);
   lines.push(`      float dy = y - last_y;`);
   lines.push(`      gState.scrollY += dy;`);
   lines.push(`      last_y = y;`);
   lines.push(`      if (gState.scrollY > 0) gState.scrollY = 0;`);
   lines.push(`      if (gState.scrollY < -gState.maxScrollY) gState.scrollY = -gState.maxScrollY;`);
   lines.push(`    }`);
   lines.push(``);
   lines.push(`    was_touched = touched;`);
   lines.push(`  }`);
   lines.push(``);
   lines.push(` private:`);
   lines.push(`  static void handleTap(float x, float y) {`);
   lines.push(`    if (gState.currentView == VIEW_MAIN_DASHBOARD) {`);
  lines.push(`      const HitBox* boxes = nullptr;`);
  lines.push(`      int count = 0;`);
  lines.push(`      switch (gState.mainPageIndex) {`);
  project.dashboardPages.forEach((_, i) => {
    lines.push(`        case ${i}: boxes = HIT_BOXES_PAGE_${i}; count = HIT_BOX_COUNT_PAGE_${i}; break;`);
  });
  lines.push(`      }`);
  lines.push(`      for (int i = 0; i < count; i++) {`);
  lines.push(`        if (x >= boxes[i].x && x <= boxes[i].x + boxes[i].w && y >= boxes[i].y && y <= boxes[i].y + boxes[i].h) {`);
  lines.push(`          dispatchAction(boxes[i]);`);
  lines.push(`          return;`);
  lines.push(`        }`);
  lines.push(`      }`);
  lines.push(`    } else {`);
  lines.push(`      float ty = y - gState.scrollY;`);
  lines.push(`      const HitBox* boxes = nullptr;`);
  lines.push(`      int count = 0;`);
  lines.push(`      switch (gState.currentView) {`);
  project.detailViews.forEach(view => {
    const safeId = view.id.toUpperCase().replace(/-/g, '_');
    lines.push(`        case VIEW_DETAIL_${safeId}: boxes = HIT_BOXES_VIEW_${safeId}; count = HIT_BOX_COUNT_VIEW_${safeId}; break;`);
  });
  lines.push(`      }`);
  lines.push(`      for (int i = 0; i < count; i++) {`);
  lines.push(`        if (x >= boxes[i].x && x <= boxes[i].x + boxes[i].w && ty >= boxes[i].y && ty <= boxes[i].y + boxes[i].h) {`);
  lines.push(`          dispatchAction(boxes[i]);`);
  lines.push(`          return;`);
  lines.push(`        }`);
  lines.push(`      }`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`};`);

  return lines.join("\n");
}

function collectHitBoxes(comp: Component, hitBoxes: HitBoxDef[], context: { pageIndex?: number, viewId?: string }) {
  // Map all possible action fields
  const actions: { type: string, action: ActionBinding | undefined }[] = [
    { type: 'onTap', action: comp.onTap },
    { type: 'onHold', action: comp.onHold },
    { type: 'onDragStart', action: comp.onDragStart },
    { type: 'onDragEnd', action: comp.onDragEnd }
  ];

  // For now, we only support one action per component (the first one found)
  const active = actions.find(a => a.action);
  
  if (active && comp.position && comp.size) {
    hitBoxes.push({
      id: comp.id,
      x: comp.position.x,
      y: comp.position.y,
      w: comp.size.width,
      h: comp.size.height,
      ...context,
      action: parseAction(active.action!)
    });
  }
}

function parseAction(action: ActionBinding): ActionDef {
  if (action.type === "SERVICE_CALL") {
    return {
      type: "SERVICE_CALL",
      service: action.service,
      entityId: action.target?.entityId,
      dataJson: JSON.stringify(action.data || {})
    };
  }
  return {
    type: action.type as any,
    targetView: action.targetId
  };
}

function actionTypeToEnum(type: string): string {
  return `ACTION_${type}`;
}

function escapeJson(json: string): string {
  return json.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
