import type { Project } from "@vesp-cloud/schema";

export function generateUIThemeHeader(project: Project): string {
  const isRetro = project.theme?.id === "retro";
  return `#pragma once

// Generated by codegen. 1 = retro style, 0 = modern style.
#ifndef UI_THEME_RETRO
#define UI_THEME_RETRO ${isRetro ? 1 : 0}
#endif
`;
}
