import type { Project } from "@vesp-cloud/schema";

export function generateUIThemeHeader(project: Project): string {
  const isRetro = project.theme?.id === "retro";
  const accent = project.theme?.chromeAccent;

  const accentDefine = accent
    ? `#define CHROME_ACCENT_COLOR Color(${accent.r}, ${accent.g}, ${accent.b})`
    : `#define CHROME_ACCENT_COLOR RetroColors::CYAN`;

  return `#pragma once

// Generated by codegen. 1 = retro style, 0 = modern style.
#ifndef UI_THEME_RETRO
#define UI_THEME_RETRO ${isRetro ? 1 : 0}
#endif

// Chrome accent color (clock, page indicator active dot, detail title)
${accentDefine}
`;
}
