
services:
  homeassistant:
    image: homeassistant/home-assistant:dev
    container_name: ha-dev-esphome-display
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
      - ../integrations/ha-metadata-exporter/custom_components/esphome_display:/config/custom_components/esphome_display
      - ../integrations/ha-display-notifications/custom_components/esphome_display_notifications:/config/custom_components/esphome_display_notifications
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
