
services:
  homeassistant:
    image: homeassistant/home-assistant:dev
    container_name: ha-dev-esphome-display
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
      - ../custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped