version: "3.9"
services:
  app:
    build:
      dockerfile: packages/editor/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@100.82.130.136:5432/esphome
      - CONCURRENT_JOBS=4