services:
  app:
    build:
      dockerfile: packages/editor/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/esphome
      - CONCURRENT_JOBS=4
      - APP_EDITION=cloud
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esphome.rule=Host(`esphome.oesterlin.dev`)"
      - "traefik.http.services.esphome.loadbalancer.server.port=3000"
    volumes:
      - esphome_builds:/tmp/esphome-builds

volumes:
  esphome_builds:

networks:
  traefik_web:
    external: true
